apiVersion: apps/v1
kind: Deployment
metadata:
  name: bsc-bkgrnd-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: bsc-bkgrnd
  template:
    metadata:
      labels:
        app: bsc-bkgrnd
    spec:
      containers:
        - name: bsc-bkgrnd
          image: yash5090/bsc-bkgrnd:latest # Replace with the actual image tag
          ports:
            - containerPort: 5000 # Replace with the port your Tetris game listens on
